# Generated by Django 3.1.1 on 2020-10-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201018_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name': 'Replie'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User'},
        ),
    ]
